version: "3.9"
services:
  pong-node-1:
    container_name: pong_node_1
    build:
      context: .
    environment:
      # - NODE_NAME="my-node-1"
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - RABBIT_MQ_HOST=rabbit_mq
      - RABBIT_MQ_PORT=5672
    ports:
      - 9001:8081
    networks:
      - demokit
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "pong-node-1"

  pong-node-2:
    container_name: pong_node_2
    build:
      context: .
    environment:
      # - NODE_NAME="my-node-2"
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - RABBIT_MQ_HOST=rabbit_mq
      - RABBIT_MQ_PORT=5672
    ports:
      - 9002:8081
    networks:
      - demokit
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "pong-node-2"

networks:
  demokit:
    name: demokit